# Generated by Django 3.2.5 on 2021-07-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210714_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='slug',
            new_name='description',
        ),
    ]
